require("game/view/mainscene/onescene/Onescene")
require("game/comm/Shieldingscreen")
require("data/Datatext")
require("game/view/mainscene/message/Message")
require("game/view/mainscene/merge/Merge")
require("game/comm/UItool")